### ISSUE TITLE
t/xs tests fail without List::MoreUtils::XS installed

### ISSUE THREAD

**Issue by kyzn** [perl5-utils/List-MoreUtils#27] opened 2017-09-01 04:29 UTC
Hi! I was recently updating my modules, and it failed for List::MoreUtils. All tests in t/ has passed fine, but nothing in t/xs has passed. Here's a sample error, but all looks the same.

```
Can't locate List/MoreUtils/XS.pm in @INC (you may need to install the List::MoreUtils::XS module) (@INC contains: ....... )
BEGIN failed--compilation aborted at ~/.cpanm/work/1504238889.5695/List-MoreUtils-0.423/blib/lib/List/MoreUtils.pm line 20.
Compilation failed in require at t/xs/after.t line 7.
BEGIN failed--compilation aborted at t/xs/after.t line 7.
t/xs/after.t ......................
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
```

This went away after I installed List::MoreUtils::XS.

**Comment by Grinnz** [comment] 2017-09-07 23:19
this is a duplicate of https://rt.cpan.org/Ticket/Display.html?id=122875 and should be fixed in the latest version.

**Comment by rehsack** [comment] 2017-11-06 12:02
@Grinnz Thanks for guiding @kyzn.

Since RT is the official bug-tracker, people should not expect that GitHub issues are actively watched - but some just shoot and don't care about the extra effort the maintainers and contributors have to drag all pieces together.

As long as they're patient and do not rumble, I'm fine and watch before start new release work - maybe weeks / months "to late", but *shrug* :)

**Closed by rehsack** 2017-11-06 12:02 UTC
